## Write a Numpy program to compute the multiplication of two given matrixes

In [1]:
import numpy as np 

In [2]:
a = np.random.randint(0,100,(3,3))
b = np.random.randint(0,100,(3,3))
z = a * b 

## Write a NumPy program to compute the determinant of a given square array

In [4]:
print(np.linalg.det(a))

147449.99999999994


In [5]:
print(np.linalg.det(b))

118344.0000000002


## Write a NumPy program to compute the cross product of two given vectors

In [6]:
print(np.cross(a,b))

[[  900 -4944   352]
 [-1656   468  2042]
 [ 1395   849 -1712]]


## Write a NumPy program to compute the condition number of a given matrix

In [10]:
print(np.linalg.cond(a))


12.119096595844578


## Write a NumPy program to compute the inverse of a given matrix

In [11]:
print(np.linalg.inv(a))


[[ 0.00996948  0.00406918 -0.00956256]
 [-0.02217701  0.02360122 -0.01546287]
 [ 0.0224822  -0.03095965  0.04442184]]
